# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 杰哥的{运维,编程}小笔记
email: noc@jiegec.ac.cn
description: > # this means to ignore newlines until "baseurl:"
  This is the personal blog of Jiajie Chen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jiege.ch" # the base hostname & protocol for your site
github_username:  jiegec

# Build settings
markdown: kramdown

tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag

permalink: pretty
tag_permalink_style: pretty

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

plugins:
  - jekyll-mentions
  - jekyll-sitemap
