# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jiegec's blog
email: jiegec@qq.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal blog of Jiege Chen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jiegec.github.io" # the base hostname & protocol for your site
github_username:  jiegec

# Build settings
markdown: kramdown

tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag

permalink: pretty
tag_permalink_style: pretty
