# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jiegec's blog
email: jiegec@qq.comB
description: > # this means to ignore newlines until "baseurl:"
  This is the personal blog of Jiege Chen.
  I'm a Senior Two student in China. Interested in programming and mathematics.
  Find me by my email jiegec@qq.com.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jiegec.github.io" # the base hostname & protocol for your site
twitter_username: tank_jackchen
github_username:  jiegec

# Build settings
markdown: kramdown
