baseURL = "https://jia.je"
languageCode = "en-us"
title = "杰哥的{运维,编程,调板子}小笔记"
theme = "minos"
publishDir = "../jiegec.github.io"
pagniate = 10
disqusShortname = "jiegec"
googleAnalytics = "G-3109FRSVTT"

[taxonomies]
  category = "category"
	tags = "tags"

[permalinks]
  ctf = "/:section/:year/:month/:day/:filename/"
  crypto = "/:section/:year/:month/:day/:filename/"
  devops = "/:section/:year/:month/:day/:filename/"
  hardware = "/:section/:year/:month/:day/:filename/"
  life = "/:section/:year/:month/:day/:filename/"
  logo = "/:section/:year/:month/:day/:filename/"
  meta = "/:section/:year/:month/:day/:filename/"
  misc = "/:section/:year/:month/:day/:filename/"
  networking = "/:section/:year/:month/:day/:filename/"
  news = "/:section/:year/:month/:day/:filename/"
  os = "/:section/:year/:month/:day/:filename/"
  others = "/:section/:year/:month/:day/:filename/"
  programming = "/:section/:year/:month/:day/:filename/"
  software = "/:section/:year/:month/:day/:filename/"
  speech = "/:section/:year/:month/:day/:filename/"
  system = "/:section/:year/:month/:day/:filename/"
  unboxing = "/:section/:year/:month/:day/:filename/"

[params]
  smartToc = true
  katex = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"

  [[menu.main]]
    identifier = "projects"
    name = "项目"
    url = "/projects/readme/"

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"

  [[menu.main]]
    identifier = "category"
    name = "分类"
    url = "/category/"

  [[menu.main]]
    identifier = "feed"
    name = "订阅"
    url = "/feed.xml"

  [[menu.main]]
    identifier = "open-source-contributions"
    name = "开源"
    url = "/open-source-contributions/"
  
  [[menu.main]]
    identifier = "series"
    name = "系列"
    url = "/series/"

  [[menu.main]]
    identifier = "kb"
    name = "知识库"
    url = "/kb/"

# allow raw html e.g. WaveDrom
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
