baseURL = "https://jiege.ch"
languageCode = "en-us"
title = "杰哥的{运维,编程,调板子}小笔记"
theme = "minos"
publishDir = "../jiegec.github.io"
pagniate = 10
disqusShortname = "jiegec"

[taxonomies]
    category = "category"
	tags = "tags"

[permalinks]
  ctf = "/:section/:year/:month/:day/:filename/"
  devops = "/:section/:year/:month/:day/:filename/"
  hardware = "/:section/:year/:month/:day/:filename/"
  life = "/:section/:year/:month/:day/:filename/"
  logo = "/:section/:year/:month/:day/:filename/"
  meta = "/:section/:year/:month/:day/:filename/"
  misc = "/:section/:year/:month/:day/:filename/"
  networking = "/:section/:year/:month/:day/:filename/"
  news = "/:section/:year/:month/:day/:filename/"
  os = "/:section/:year/:month/:day/:filename/"
  others = "/:section/:year/:month/:day/:filename/"
  programming = "/:section/:year/:month/:day/:filename/"
  software = "/:section/:year/:month/:day/:filename/"
  speech = "/:section/:year/:month/:day/:filename/"
  system = "/:section/:year/:month/:day/:filename/"
  unboxing = "/:section/:year/:month/:day/:filename/"

[params]
    smartToc = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"

  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"

  [[menu.main]]
    identifier = "projects"
    name = "项目"
    url = "/projects/"

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"

  [[menu.main]]
    identifier = "category"
    name = "分类"
    url = "/category/"

  [[menu.main]]
    identifier = "feed"
    name = "订阅"
    url = "/feed.xml"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
