site_description: 杰哥的{运维,编程,调板子}小笔记
site_name: 杰哥的{运维,编程,调板子}小笔记
site_url: https://jia.je/

theme:
  name: material
  language: zh

nav:
  - 博客: index.md
  - 关于: about.md
  - 开源: open-source-contributions.md
  - 标签: tags.md
  - 系列: series.md
  - 项目: projects/README.md
  - 工具: tools.md

plugins:
  - tags:
      tags_file: tags.md
  - blog:
      post_url_format: "{categories}/{date}/{file}"
      blog_dir: .
      archive_toc: true
      categories_toc: true
      blog_toc: true
  - rss:
      abstract_chars_count: -1
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
        as_update: date
      categories:
        - categories
        - tags

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
