site_name: 杰哥的{运维,编程,调板子}小笔记

theme:
  name: material

nav:
  - index.md

plugins:
  - blog:
      post_url_format: "{categories}/{date}/{file}"
      blog_dir: .
      archive_name: 归档
      categories_name: 分类
      # blog_toc: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
