site_description: 杰哥的{运维,编程,调板子}小笔记
site_name: 杰哥的{运维,编程,调板子}小笔记
site_url: https://jia.je/

theme:
  name: material
  language: zh
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.copy
    - toc.follow
    - toc.integrate

nav:
  - 博客: index.md
  - 关于: about.md
  - 开源: open-source-contributions.md
  - 标签: tags.md
  - 知识库: "/kb/"
  - 系列: series.md
  - 项目: projects/README.md
  - 工具: tools.md
  - 订阅: "/feed.xml"

plugins:
  - tags:
      tags_file: tags.md
  - blog:
      post_url_format: "{categories}/{date}/{file}"
      blog_dir: .
      archive_toc: true
      categories_toc: true
      blog_toc: true
  - rss:
      abstract_chars_count: -1
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
        as_update: date
      categories:
        - categories
        - tags
  - search:
  - git-revision-date-localized:
      enabled: !ENV [DEPLOY, false]
      enable_creation_date: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
