name: Deploy GitHub Pages to external repository

on:
  https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
   push:
     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for git history
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: Gr1N/setup-poetry@v9
      - run: poetry install
      - run: cd docs/data && poetry run python3 plot.py
      - run: DEPLOY=true poetry run mkdocs build
      - run: cd site && ln -s feed_rss_updated.xml feed.xml
